version: "3.9"

services:
  user_app_servicex:
    build:
      context: .
      dockerfile: ./docker/user_app/Dockerfile
    container_name: user_app_container
    ports:
      - "5555:5555"
    volumes:
      - ./src/user_app:/app
    environment:
          - DB_HOST=ua_devdb
          - DB_NAME=ua_db
          - DB_USER=postgres
          - DB_PASSWORD=postgres
    depends_on:
      - ua_db

  ua_db:
    image: postgres:13-alpine
    volumes:
      - ua_postgres-dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ua_devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  transactions_app_service:
    build:
      context: .
      dockerfile: ./docker/transactions_app/Dockerfile
      args:
        - DEV=true
    container_name: transactions_app_container
    ports:
      - "8800:8800"
    volumes:
      - ./src/transactions_app:/app
    command:
#      sh -c "python manage.py wait_for_db &&
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8800"
    environment:
      - DB_HOST=ta_db
      - DB_NAME=ta_devdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - ta_db

  ta_db:
    image: postgres:13-alpine
    volumes:
      - ta_postgres-dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ta_devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  ta_postgres-dev-db-data:
  ua_postgres-dev-db-data:
